name: Run Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-xdist allure-pytest
        pip install playwright
        playwright install

    # 4. Run tests
    - name: Run tests with pytest
      run: |
        pytest -n auto --alluredir=allure-results

    - name: Generate Allure HTML Report
      run: |
        pip install allure-commandline
        allure generate allure-results --clean -o allure-report

    - name: Deploy Allure Report
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./allure-report

    # 5. Upload Allure results as artifacts
    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
        reporter: allure



    - name: Run tests inside Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        xvfb-run -a pytest -n auto --alluredir=allure-results   


    # # 6. Generate Allure HTML Report
    # - name: Generate Allure report
    #   uses: ashikkumar23/[email protected]
    #   with:
    #     ALLURE_RESULTS_PATH: allure-results
    #     ALLURE_REPORT_PATH: allure-report

    # # 7. Upload Allure HTML report
    # - name: Upload Allure HTML as artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: allure-report
    #     path: allure-report
